car_rental/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/urls.py
from django.contrib import admin
from django.urls import path, include

from company import views

urlpatterns = [
    path('', views.index_page, name='index'),
    path('brand/', views.brand_page, name='brand'),
    path('contact/', views.contact_page, name='contact'),
    path('fine/', views.fine_page, name='fine'),
    path('listing/', views.listing_page, name='listing'),
    path('payment/<int:pk>/', views.payment_page, name='payment'),
    path('supply/', views.supply_page, name='supply'),
]

company/models.py
from django.db import models
from django.db.models import F


class Company(models.Model):
    company_name = models.CharField(max_length=100, unique=True)
    tin = models.CharField(max_length=100)
    number_of_employee = models.IntegerField()
    number_of_inventory = models.IntegerField(null=True, blank=True, default=0, help_text='leave it blank')

    def __str__(self):
        return str(self.company_name)


class Dealer(models.Model):
    company = models.ForeignKey(Company, null=True, on_delete=models.SET_NULL)
    dealer_name = models.CharField(max_length=100)
    supply_rate = models.FloatField()
    dealer_location = models.TextField(max_length=100)

    def __str__(self):
        return str(self.dealer_name)


class Manufacture(models.Model):
    dealer = models.ForeignKey(Dealer, null=True, on_delete=models.SET_NULL, related_name='manufacture')
    manufacture_name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    num_of_car_company = models.IntegerField()

    def __str__(self):
        return str(self.manufacture_name)


class CarCompany(models.Model):
    manufacture = models.ForeignKey(Manufacture, null=True, on_delete=models.SET_NULL, related_name='car_company')
    company_name = models.CharField(max_length=100)
    num_of_car_model = models.IntegerField()
    volume_of_production = models.IntegerField()

    def __str__(self):
        return str(self.company_name)


class Inventory(models.Model):
    type = (
        ('Indoor', 'Indoor'),
        ('Outdoor', 'Outdoor'),
    )
    company = models.ForeignKey(Company, null=True, on_delete=models.SET_NULL)
    type_of_inventory = models.CharField(max_length=100, choices=type)
    capacity = models.CharField(max_length=100)
    location = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        created = self.pk is None
        super(Inventory, self).save(*args, **kwargs)
        print(2)
        if created:
            print(1)
            Company.objects.filter(company_name=self.company).update(
                number_of_inventory=F('number_of_inventory') + 1)

    def __str__(self):
        return str(self.location)


class Vehicle(models.Model):
    inventory = models.ForeignKey(Inventory, null=True, on_delete=models.SET_NULL)
    plate_number = models.CharField(max_length=100, unique=True, null=True)
    vin_number = models.CharField(max_length=100, unique=True, null=True)

    def __str__(self):
        return str(self.vin_number) + ' -|- ' + str(self.plate_number)


class Sales(models.Model):
    price = models.FloatField()
    vehicle = models.OneToOneField(Vehicle, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.price) + '$'


class CarModel(models.Model):
    model_name = models.CharField(max_length=100, )
    model_year = models.DateField()
    body_type = models.CharField(max_length=100, )
    image = models.TextField()
    rent_amount = models.IntegerField(default=0)
    vehicle = models.OneToOneField(Vehicle, null=True, on_delete=models.SET_NULL, related_name='vehicle_car')
    car_company = models.ForeignKey(CarCompany, null=True, on_delete=models.SET_NULL, related_name='vehicle_car')

    def __str__(self):
        return str(self.model_name)


class Customer(models.Model):
    sex = {
        ('Male', 'Male'),
        ('Female', 'Female'),
    }
    full_name = models.CharField(max_length=100)
    dob = models.DateField()
    gender = models.CharField(max_length=100, choices=sex)
    passport = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100)
    insurance = models.CharField(max_length=100)
    licence = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

    def __str__(self):
        return str(self.full_name)


class Fine(models.Model):
    fine_cases = models.CharField(max_length=100)
    fine_amount = models.CharField(max_length=100)

    def __str__(self):
        return str(self.fine_cases)


class CarOption(models.Model):
    car_color = (
        ('White', 'White'),
        ('Black', 'Black'),
        ('Gray', 'Gray'),
        ('Red', 'Red'),
        ('Blue', 'Blue'),
    )
    wheel = (
        ('18', '18'),
        ('19', '19')
    )
    material = (
        ('Cloth', 'Cloth'),
        ('Leather', 'Leather'),
    )
    engine = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3')
    )
    car_model = models.ForeignKey(CarModel, null=True, on_delete=models.SET_NULL)
    power = models.CharField(max_length=100, help_text='km/h')
    battery_capacity = models.CharField(max_length=100, help_text='KW')
    color = models.CharField(max_length=100, choices=car_color)
    interior_material = models.CharField(max_length=100, choices=material)
    size_of_wheel = models.CharField(max_length=100, choices=wheel)
    number_of_engine = models.CharField(max_length=100, choices=engine)

    def __str__(self):
        return 'Model: ' + str(self.car_model) + ' Range: ' + str(self.power) + ' Engine: ' + str(self.number_of_engine)


class PaymentMethod(models.Model):
    method = (
        ('Visa', 'Visa'),
        ('Mastercard', 'Mastercard'),
        ('PayPal', 'PayPal'),
    )
    customer = models.OneToOneField(Customer, null=True, on_delete=models.SET_NULL)
    car = models.ForeignKey(CarOption, null=True, on_delete=models.SET_NULL)
    payment_type = models.CharField(max_length=100, choices=method)
    amount = models.FloatField()
    card_number = models.CharField(max_length=100, null=True)
    cvv = models.CharField(max_length=10, null=True)
    start_day = models.DateTimeField(null=True)
    end_day = models.DateTimeField(null=True)
    total_day = models.CharField(max_length=10, null=True)

    def __str__(self):
        return str(self.customer)


class Contact(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    text = models.TextField()

    def __str__(self):
        return str(self.email)


class Damaged(models.Model):
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    fine = models.ForeignKey(Fine, null=True, on_delete=models.SET_NULL)
    car_option = models.ForeignKey(CarOption, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.customer)

templates/others/brand.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <div class="site-wrap" id="home-section">
        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>


        <div class="hero inner-page" style="background-image: url({% static 'images/hero_1_a.jpg' %});">

            <div class="container">
                <div class="row align-items-end ">
                    <div class="col-lg-5">
                        <div class="intro">
                            <h1><strong>Our Company</strong></h1>
                            <div class="custom-breadcrumbs"><a href="{% url 'index' %}">Home</a> <span
                                    class="mx-2">/</span>
                                <strong>Our Company</strong>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        {% for company in company %}
            <div class="site-section">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 order-lg-2">
                            <img src="{% static 'images/hero_2.jpg' %}" alt="Image" class="img-fluid rounded">
                        </div>
                        <div class="col-lg-6 mr-auto bg-light">
                            <div class="container">
                                <div class="row justify-content-center text-center ">
                                    <div class="col-md">
                                        <h2 class="mb-4 pt-4">Our Company {{ company.company_name }}</h2>
                                    </div>
                                </div>
                                <div class="row align-items-stretch">
                                    <div class="col-lg col-md-6 mb-5">

                                        <div class="post-entry-1-contents">
                                            <div class="mb-3 border-bottom">
                                                <div class="listing-feature pr-4 w-500">
                                                    <span class="caption">TIN</span>
                                                    <span class="number pl-3">{{ company.tin }}</span>
                                                </div>
                                            </div>
                                            <div class="mb-3 border-bottom pb-3">
                                                <div class="listing-feature pr-4 d-flex">
                                                    <span class="caption">Number_of_employee</span>
                                                    <span class="number pl-3">{{ company.number_of_employee }}</span>
                                                </div>
                                            </div>
                                            <div class="mb-3 border-bottom pb-3">
                                                <div class="listing-feature pr-4 d-flex">
                                                    <span class="caption">Number_of_inventory</span>
                                                    <span class="number ml-3">{{ company.number_of_inventory }}</span>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% for foo in company.inventory_set.all %}
                <div class="site-section">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-6 ">
                                <img src="{% static 'images/brand_'%}{{ forloop.counter }}.png" alt="Image" class="img-fluid rounded">
                            </div>
                            <div class="col-lg-6 ml-auto bg-light">
                                <div class="row justify-content-center text-center ">
                                    <div class="col-md-6">
                                        <h2 class="mb-4">Our Inventories</h2>
                                    </div>
                                </div>
                                <div class="row align-items-stretch">
                                    <div class="col-lg col-md">

                                        <div class="post-entry-1-contents">
                                            <div class="d-block d-md-flex mb-3 border-bottom pb-3">
                                                <div class="listing-feature pr-4">
                                                    <span class="caption">Type of inventory</span>
                                                    <span class="number">{{ foo.type_of_inventory }}</span>
                                                </div>
                                            </div>
                                            <div class="d-block d-md-flex mb-3 border-bottom pb-3">
                                                <div class="listing-feature pr-4">
                                                    <span class="caption">Capacity</span>
                                                    <span class="number">{{ foo.capacity }}</span>
                                                </div>
                                            </div>
                                            <div class="d-block d-md-flex mb-3 border-bottom pb-3">
                                                <div class="listing-feature pr-4">
                                                    <span class="caption">Location</span>
                                                    <span class="number">{{ foo.location }}</span>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endfor %}
    </div>
{% endblock %}

templates/others/contact.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <div class="hero inner-page" style="background-image: url({% static 'images/hero_1_a.jpg' %});">

        <div class="container">
            <div class="row align-items-end ">
                <div class="col-lg-5">

                    <div class="intro">
                        <h1><strong>Contact</strong></h1>
                        <div class="custom-breadcrumbs"><a href="{% url 'index' %}">Home</a> <span class="mx-2">/</span>
                            <strong>Contact</strong></div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="site-section bg-light" id="contact-section">
        <div class="container">
            <div class="row justify-content-center text-center">
                <div class="col-7 text-center mb-5">
                    <h2>Contact Us Or Use This Form To Rent A Car</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo assumenda, dolorum necessitatibus
                        eius
                        earum voluptates sed!</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 mb-5">
                    <form action="#" method="post">
                        {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-md-6 mb-4 mb-lg-0">
                                <input name="first_name" type="text" class="form-control" placeholder="First name">
                            </div>
                            <div class="col-md-6">
                                <input name="last_name" type="text" class="form-control" placeholder="Last name">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-12">
                                <input name="email" type="email" class="form-control" placeholder="Email address">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-12">
                                <textarea name="text" id="" class="form-control" placeholder="Write your message." cols="30"
                            rows="10"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-6 mr-auto">
                                <input type="submit" class="btn btn-block btn-primary text-white py-3 px-5"
                                       value="Send Message">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-4 ml-auto">
                    <div class="bg-white p-3 p-md-5">
                        <h3 class="text-black mb-4">Contact Info</h3>
                        <ul class="list-unstyled footer-link">
                            <li class="d-block mb-3">
                                <span class="d-block text-black">Address:</span>
                                <span>34 Street Name, City Name Here, United States</span>
                            </li>
                            <li class="d-block mb-3"><span
                                    class="d-block text-black">Phone:</span><span>+1 242 4942 290</span></li>
                            <li class="d-block mb-3"><span class="d-block text-black">Email:</span><span>info@yourdomain.com</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/others/fine.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <div class="hero inner-page" style="background-image: url({% static 'images/hero_1_a.jpg' %});">

        <div class="container">
            <div class="row align-items-end ">
                <div class="col-lg-5">
                    <div class="intro">
                        <h1><strong>FineCases</strong></h1>
                        <div class="custom-breadcrumbs"><a href="{% url 'index' %}">Home</a> <span class="mx-2">/</span>
                            <strong>FineCases</strong>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 order-lg-2">
                    <img src="{% static 'images/hero_2.jpg' %}" alt="Image" class="img-fluid rounded">
                </div>
                <div class="col-lg-6 mr-auto bg-light">
                    <div class="container">
                        <div class="row justify-content-center text-center ">
                            <div class="col-md-6 pt-4">
                                <h2 class="mb-4">Fine Cases While Rental</h2>
                            </div>
                        </div>
                        <div class="row align-items-stretch">
                            <div class="col-lg-4 col-md-6 mb-5">

                                <div class="post-entry-1-contents">
                                    <h3 class="meta">Cases</h3>
                                    {% for foo in fine %}
                                        <div>
                                            <div style="width: 500px!important;">
                                                <span class="caption">{{ foo.fine_cases }}</span>
                                                <span class="number ml-2">{{ foo.fine_amount }}$</span>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/others/listing.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <div class="hero inner-page" style="background-image: url({% static 'images/hero_1_a.jpg' %});">
        <div class="container">
            <div class="row align-items-end ">
                <div class="col-lg-5">
                    <div class="intro">
                        <h1><strong>Listings</strong></h1>
                        <div class="custom-breadcrumbs"><a href="{% url 'index' %}">Home</a> <span class="mx-2">/</span>
                            <strong>Listings</strong></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="site-section bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-7">
                    <h2 class="section-heading"><strong>Available Cars</strong></h2>
                    <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                </div>
            </div>

            <div class="row">
                {% for obj in cars %}
                    <div class="col-md-6 col-lg-4 mb-4">

                        <div class="listing d-block  align-items-stretch">
                            <div class="listing-img h-100 mr-4">
                                <img src="{{ obj.car_model.image }}" alt="Image" class="img-fluid">
                            </div>
                            <div class="listing-contents h-100">
                                <h3>{{ obj.car_model.model_name }}</h3>
                                <div class="rent-price">
                                    <strong>{{ obj.car_model.vehicle.sales.price }}$</strong><span class="mx-1">/</span>day
                                </div>


                                <div class="d-block d-md-flex mb-3 border-bottom pb-3">
                                    <div class="listing-feature pr-4">
                                        <span class="caption">Body type</span>
                                        <span class="number">{{ obj.car_model.body_type }}</span>
                                    </div>
                                    <div class="listing-feature pr-4">
                                        <span class="caption">Model Year</span>
                                        <span class="number">{{ obj.car_model.model_year|date:"Y" }}</span>
                                    </div>
                                </div>

                                <div class="d-block d-md-flex mb-3 border-bottom pb-3">
                                    <div class="listing-feature pr-4">
                                        <span class="caption">Number of engine</span>
                                        <span class="number">{{ obj.number_of_engine }}</span>
                                    </div>
                                    <div class="listing-feature pr-4">
                                        <span class="caption">Size of wheel</span>
                                        <span class="number">{{ obj.size_of_wheel }}</span>
                                    </div>
                                </div>

                                <div class="d-block d-md-flex mb-3 border-bottom pb-3">
                                    <div class="listing-feature pr-4">
                                        <span class="caption">Interior material</span>
                                        <span class="number">{{ obj.interior_material }}</span>
                                    </div>
                                    <div class="listing-feature pr-4">
                                        <span class="caption">color</span>
                                        <span class="number">{{ obj.color }}</span>
                                    </div>
                                </div>

                                <div class="d-block d-md-flex mb-3 border-bottom pb-3">
                                    <div class="listing-feature pr-4">
                                        <span class="caption">Battery capacity</span>
                                        <span class="number">{{ obj.battery_capacity }}</span>
                                    </div>
                                    <div class="listing-feature pr-4">
                                        <span class="caption">Range</span>
                                        <span class="number">{{ obj.power }}</span>
                                    </div>
                                </div>
                                <div class="d-block d-md-flex mb-3 border-bottom pb-3">
                                    <div class="listing-feature pr-4">
                                        <span class="caption">Company</span>
                                        <span class="number">{{ obj.car_model.vehicle.inventory.company}}</span>
                                    </div>
                                    <div class="listing-feature pr-4">
                                        <span class="caption">Location</span>
                                        <div class="text-truncate">{{ obj.car_model.vehicle.inventory|truncatechars:25}}</div>
                                    </div>
                                </div>
                                <div style="display: flex;">
                                    <p style="margin: auto;"><a href="{% url 'payment' obj.id %}"
                                                                class="btn btn-primary btn-primary">Rent Now</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="container p-4">
                <nav aria-label="Page navigation example">
                    {#                    <ul class="pagination justify-content-center">#}
                    {#                        {% if cars.has_previous and cars.number != 2 %}#}
                    {#                            <li class="page-item">#}
                    {#                                <a class="page-link" href="?page=1">&laquo; first</a>#}
                    {#                            </li>#}
                    {#                            <li class="page-item">#}
                    {#                                <a class="page-link" href="?page={{ cars.previous_page_number }}">previous</a>#}
                    {#                            </li>#}
                    {#                        {% else %}#}
                    {#                            <li class="page-item">#}
                    {#                                <a class="page-link" href="?page=1">&laquo; first</a>#}
                    {#                            </li>#}
                    {#                        {% endif %}#}
                    {#                        <li class="page-item disabled">#}
                    {#                            <a class="page-link" href="#" tabindex="-1">{{ cars.number }}</a>#}
                    {#                        </li>#}
                    {##}
                    {#                        <span class="current">#}
                    {#                            Page {{ cars.number }} of {{ cars.paginator.num_pages }}#}
                    {#                        </span>#}
                    {##}
                    {#                        {% if cars.has_next %}#}
                    {#                            <li class="page-item">#}
                    {#                                <a class="page-link" href="?page={{ cars.next_page_number }}">next</a>#}
                    {#                            </li>#}
                    {#                            <li class="page-item">#}
                    {#                                <a class="page-link" href="?page={{ cars.paginator.num_pages }}">last&raquo;</a>#}
                    {#                            </li>#}
                    {#                        {% endif %}#}
                    {#                    </ul>#}
                    <ul class="pagination justify-content-center">

{#                        {% if cars.has_previous %}#}
{#                            <li class="page-item">#}
{#                                <a class="page-link" href="?page={{ cars.previous_page_number }}">#}
{#                                    <i class="fa fa-chevron-left" aria-hidden="true"></i>#}
{#                                </a>#}
{#                            </li>#}
{#                        {% endif %}#}

                        {% if cars.number|add:'-4' > 1 %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ cars.number|add:'-5' }}">&hellip;</a>
                            </li>
                        {% endif %}

                        {% for i in cars.paginator.page_range %}
                            {% if cars.number == i %}
                                <li class="page-item active" style="cursor: pointer;">
                                    <a class="page-link">{{ i }}</a>
                                </li>
                            {% elif i > cars.number|add:'-5' and i < cars.number|add:'5' %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        {% if cars.paginator.num_pages > cars.number|add:'4' %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ cars.number|add:'5' }}">&hellip;</a>
                            </li>
                        {% endif %}

{#                        {% if cars.has_next %}#}
{#                            <li class="page-item">#}
{#                                <a class="page-link" href="?page={{ cars.next_page_number }}">#}
{#                                    <i class="fa fa-chevron-right" aria-hidden="true"></i>#}
{#                                </a>#}
{#                            </li>#}
{#                        {% endif %}#}

                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}